name: build-sphinx-html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-sphinx:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
        name: Set up Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          make  dirhtml
          touch build/dirhtml/.nojekyll
      
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        name: Deploy 🚀
        with:
          branch: gh-pages
          folder: build/dirhtml
          clean: true
          single-commit: true